using System;

namespace First_50_Problems
{
    public static class Problem2
    {
        //-----
        // Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
        // By starting with 1 and 2, the first 10 terms will be:
        // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        // By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
        // find the sum of the even-valued terms.
        //-----

        public static long SumOfEvenFibonacciNumbers(long n)
        {
            long result = 0;
            if (n<2)
            {
                return result;
            }
            else
            {
                result = 2;
            }
            int n1 = 1;
            int n2 = 2;
            int n3;
            for (long i = 3; i < n; i++)
            {
                n3 = n1 + n2;
                if (n3 % 2 == 0)
                {
                    result += n3;
                }
                n1 = n2;
                n2 = n3;
            }
            return result;
        }
    }
}
