using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _50_Problems
{
    class Problem2
    {
        //-----
        // Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
        // By starting with 1 and 2, the first 10 terms will be:
        // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        // By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
        // find the sum of the even-valued terms.
        //-----

        int n1 = 1;
        int n2 = 2;
        int n3 = 0;
        int sum = 2;
        int i = 3;
        Console.WriteLine("By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.");
            Console.WriteLine();
            Console.WriteLine("F(1) = 1; Sum = 0;");
            Console.WriteLine();
            Console.WriteLine("F(2) = 2; Sum = 2;");
            Console.WriteLine();
            do
            {
                n3 = n1 + n2;
                if (n3< 4000000)
                {
                    if (n3%2==0)
                    {
                        sum += n3;
                    }
    Console.WriteLine("F({0}) = {1}; Sum = {2};", i, n3, sum);
                    Console.WriteLine();
                    i++;
                    n1 = n2;
                    n2 = n3;
                }
            }
            while (n3< 4000000);
            Console.WriteLine("Answer: {0}", sum);
    }
}
